apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: mq-sender-service-post-stage
spec:
  serviceAccountName: pipeline
  triggers:
    - name: mq-sender-service-post-stage
      template:
        ref: mq-sender-service-post-stage
